language: php

php:
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

sudo: false

install: travis_retry composer install

script:
  - vendor/bin/phpunit --coverage-clover build/coverage.clover
  - vendor/bin/phpstan analyse src -c phpstan.neon --level=max --no-progress -vvv

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover
